config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

    root 'static_pages#home'
    get '/signup', to: 'users#new'
    post '/signup', to: 'users#create'  # named routes
    get '/login', to: 'sessions#new'
    post '/login', to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy'
    get '/my_store', to: 'stores#my_store'
    post '/update_store', to: 'stores#update_store'
    get '/create_food', to: 'foods#new'
    get '/search', to: 'static_pages#search'

    resources :users
    resources :account_activations, only: [:edit]
    resources :password_resets,     only: [:new, :create, :edit, :update]
    get   '/resend_activation/:email', to: 'account_activations#resend_activation', :constraints => { :email => /[^\/]+/ }
    resources :stores
    resources :foods
    resources :reviews
    resources :conversations,:messages
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    mount ActionCable.server => '/cable'#khong co dong nay thi AC broadcast du lieu nhung cacs client se khong nhan duoc gi dau.
end

app/models/store.rb
class Store < ApplicationRecord
    belongs_to :user
    validates :name, presence: true, length: {maximum: 50}
    validates :address, presence: true, length: {maximum: 255}
    has_many :foods, dependent: :destroy
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
    before_action :logged_in_user, only: [:create, :update_store, :destroy, :my_store]

    def index
            @stores = Store.all.order('created_at ASC')
                .paginate(page: params[:page], per_page: 6)
    end

    def my_store
            @stores = Store.where(user_id: current_user.id)
                .order('name ASC')
                .paginate(page: params[:page], per_page: 6)
    end

    def create
        @store = Store.new(store_params)
        if @store.save
            flash[:info] = "作成しました"
            redirect_to :back
        else
            flash[:danger] = @store.errors.full_messages.join(" & ")
            redirect_to :back
        end
    end

    def show
        @store = Store.find_by(id: params[:id])
        if @store == nil
            not_found
        end
    end

    def update_store
        @store = Store.find(store_params[:id])
        if @store.update_attributes(store_params)
            flash[:success] = "更新しました"
            redirect_to :back
        else
            render 'edit'
        end
    end

    def destroy
        @store = Store.find(params[:id]).destroy
        flash[:success] = "削除しました"

        if @store.destroy
            redirect_to my_store_path
        end
    end

    private
        def store_params
            params.require(:store).permit(:name, :address, :user_id, :id)
        end

end

app/views/stores/_store.html.erb
<tr>
    <td><%= link_to store.name, store %></td>
    <td><%= store.address %></td>
    <td><%= store.foods.count %></td>
    <td><div class="btn btn-warning edit-store" data-name="<%= store.name %>" data-address="<%= store.address %>" data-id="<%= store.id %>" data-toggle="modal" data-target="#myModal">編集</td>
    <td>
        <div class="setting">
            <div class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    <b class="glyphicon glyphicon-remove"></b>
                </a>
                <ul class="dropdown-menu">
                    <li><%= link_to "ストアー削除?", store_path(id: store.id), method: :delete, remote: true %></li>
                </ul>
            </div>
        </div>
    </td>
</tr>

app/views/stores/index.html.erb
<% provide(:title, "私の店") %>
<div class="index-users">
    <div class="container">
        <div class="list-users">
            <div class="container">
                <% @stores.each do |store| %>
                    <% @store = store %>
                    <%= render store %>
                <% end %>
            </div>
            <%= will_paginate @stores, class: "pagination-users" %>
        </div>
    </div>
</div>

app/views/stores/my_store.html.erb
<% provide(:title, "私の店") %>
<div class="index-users">
    <div class="container">
        <div class="col-xs-8">
            <table class="table table-bordered center">
                <thead style="background-color: blue;color: white">
                    <tr>
                        <th>店名</th>
                        <th>アドレス</th>
                        <th>店内の食品</th>
                        <th> </th>
                        <th> </th>
                    </tr>
                </thead>
                <tbody>
                    <% @stores.each do |store| %>
                        <% @store = store %>
                        <%= render store %>
                    <% end %>
                </tbody>
            </table>
            <%= will_paginate @stores, class: "pagination-users" %>
        </div>
        <div class="col-xs-4 add-store">
          <h3 class="text primary">店追加</h3>
          <%= form_for(:store, url: stores_path) do |f| %>
                <%= f.label "ストアー名", class: "name" %>
                <%= f.text_field :name, :value => nil, placeholder: "Nobita レストラン", class: 'form-control' %>
                <%= f.label "アドレス", class: "name" %>
                <%= f.text_field :address, :value => nil, placeholder: "43 Nguyen Chi Thanh Ha Noi", class: 'form-control' %>
                <%= f.hidden_field :user_id, :value => current_user.id %>
                <%= f.submit "作成する !", class: "btn-success btn" %>
          <% end %>
          <div class="hidden" id="edit-store-area">
              <h3 class="text primary">店編集</h3>
                <%= form_for(:store, url: update_store_path) do |f| %>
                    <%= f.label "ストアー名", class: "name"%>
                    <%= f.text_field :name, :value => nil, placeholder: "Nobita レストラン", class: 'form-control edit-store-name' %>
                    <%= f.label "アドレス", class: "name" %>
                    <%= f.text_field :address, :value => nil, placeholder: "43 Nguyen Chi Thanh Ha Noi", class: 'form-control edit-store-address' %>
                    <%= f.hidden_field :user_id, :value => current_user.id %>
                    <%= f.hidden_field :id, :value => nil, class: 'edit-store-id'%>
                    <%= f.submit "更新", class: "btn-warning btn" %>
                <% end %>
          </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $('.edit-store').on('click', function() {
    $('#edit-store-area').removeClass('hidden');
    $('.edit-store-name').val($(this).data('name'));
    $('.edit-store-address').val($(this).data('address'));
    $('.edit-store-id').val($(this).data('id'));
});
</script>