config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

    root 'static_pages#home'
    get '/signup', to: 'users#new'
    post '/signup', to: 'users#create'  # named routes
    get '/login', to: 'sessions#new'
    post '/login', to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy'
    get '/my_store', to: 'stores#my_store'
    post '/update_store', to: 'stores#update_store'
    get '/create_food', to: 'foods#new'
    get '/search', to: 'static_pages#search'

    resources :users
    resources :account_activations, only: [:edit]
    resources :password_resets,     only: [:new, :create, :edit, :update]
    get   '/resend_activation/:email', to: 'account_activations#resend_activation', :constraints => { :email => /[^\/]+/ }
    resources :stores
    resources :foods
    resources :reviews
    resources :conversations,:messages
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    mount ActionCable.server => '/cable'#khong co dong nay thi AC broadcast du lieu nhung cacs client se khong nhan duoc gi dau.
end

app/models/user.rb
class User < ApplicationRecord
    attr_accessor :remember_token, :activation_token, :reset_token
    before_save   :downcase_email
    before_create :create_activation_digest
    validates :name, presence: true, length: {maximum: 50}
    VALIDATE_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :email, presence: true, length: {maximum: 255},
                      format: {with: VALIDATE_EMAIL_REGEX},
                      uniqueness: {case_sensitive: false}
    has_secure_password
    mount_uploader :avatar, AvatarUploader
    validates :password, presence: true, length: {minimum: 8}, allow_nil: true
    validate :avatar_size
    has_many :stores, dependent: :destroy
    has_many :reviews, dependent: :destroy    
    has_many :conversations, ->(user) { unscope(:where).where("user1_id = :id OR user2_id = :id", id: user.id) }
    # Returns the hash digest of the given string.
    def self.digest string
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end

    # Returns a random token.
    def self.new_token
        SecureRandom.urlsafe_base64
    end

    # Remembers a user in the database for use in persistent sessions.
    def remember
        self.remember_token = User.new_token
        update_attribute(:remember_digest, User.digest(remember_token))
    end

    # Returns true if the given token matches the digest.
    def authenticated?(attribute, token)
        digest = send("#{attribute}_digest")
        return false if digest.nil?
        BCrypt::Password.new(digest).is_password?(token)
    end

    # Forgets a user.
    def forget
        update_attribute(:remember_digest, nil)
    end

    # Activates an account.
    def activate
        update_attribute(:activated,    true)
        update_attribute(:activated_at, Time.zone.now)
    end

    # Sends activation email.
    def send_activation_email
        UserMailer.account_activation(self).deliver_now
    end

    def resend_activation_email
        self.send(:create_activation_digest)
        self.send_activation_email
        self.save
    end

    # Sets the password reset attributes.
    def create_reset_digest
        self.reset_token = User.new_token
        update_attribute(:reset_digest,  User.digest(reset_token))
        update_attribute(:reset_sent_at, Time.zone.now)
    end

    # Sends password reset email.
    def send_password_reset_email
        UserMailer.password_reset(self).deliver_now
    end

    # Returns true if a password reset has expired.
    def password_reset_expired?
        reset_sent_at < 2.hours.ago
    end

    private
        def avatar_size
            if avatar.size > 5.megabytes
                error.add(:avatar, "5MB未満にする必要があります")
            end
        end

        # Converts email to all lower-case.
        def downcase_email
            self.email = email.downcase
        end

        # Creates and assigns the activation token and digest.
        def create_activation_digest
            self.activation_token  = User.new_token
            self.activation_digest = User.digest(activation_token)
        end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :logged_in_user, only: [:edit, :update, :delete, :index]
    before_action :correct_user, only: [:edit, :update]
    before_action :admin_user, only: :destroy

    def index
        @users = User.all.order('name ASC')
            .paginate(page: params[:page], per_page: 6)
    end

    def new
        @user = User.new
    end

    def edit
        @user = User.find(params[:id])
    end

    def destroy
        User.find(params[:id]).destroy
        flash[:success] = "削除しました"
    end

    def update
        @user = User.find(params[:id])
        if @user.update_attributes(user_params)
            flash[:success] = "更新しました"
            redirect_to @user
        else
            render 'edit'
        end
    end

    def show
        @user = User.find_by(id: params[:id])
        if @user == nil
            not_found
        else
            @user1 = @user

            redirect_to root_path
        end
    end

    def create
        @user = User.new(user_params)
        if @user.save
            @user.send_activation_email
            flash[:info] = "メールを確認してアカウントを有効にしてください。"
            redirect_to root_url
        else
            render 'new'
        end
    end

    private
        def user_params
            params.require(:user).permit(:name, :email, :password,
                                         :password_confirmation, :avatar)
        end

        # Before filters

        # Confirms the correct user
        def correct_user
            @user = User.find_by(id: params[:id])
            if @user == nil
                not_found
            else
                redirect_to root_url unless current_user?(@user)
            end
        end
end

app/views/users/edit.html.erb
<% provide(:title, "ユーザー編集") %>

<div class="edit-profile">
	<div class="left-block-edit">
		<%= form_for(@user) do |f| %>
			<div class="propic-edit">
				<% if @user.avatar? %>
					<%= image_tag @user.avatar.url, id: "avatar" %>
				<% else %>
					<%= image_tag @user.avatar.default_url("avatar_default.jpg"), id: "avatar"%>
				<% end %>
				<%= f.file_field :avatar, accept: "image/jpeg,image/gif,image/png",    id: "upload-pic" %>
				<a class="upload-new-pic" href="#">
					<i class="fa fa-camera" aria-hidden="true"></i>アバター更新
				</a>
			</div>
			<div class="name-edit">
				<% if @user.errors[:name].length != 0%>
					<div class="error-messages text-danger"><%= @user.errors[:name][0] %></div>
				<% end %>
				<%= f.label :name, "ユーザー名" %>
				<%= f.text_field :name, class: "form-control" %>
			</div>
			<div class="email-edit">
				<% if @user.errors[:email].length != 0%>
					<div class="error-messages text-danger"><%= @user.errors[:email][0] %></div>
				<% end %>
				<%= f.label :email, "メール" %>
				<div class="name"><%= @user.email %></div>
			</div>
			<br><br>
			<%= f.submit "更新する", class: "btn btn-warning" %>
		<% end %>
	</div>
	<div class="right-block-edit">
		<div class="alert alert-info" role="alert">
			<h3>About Update Profile</h3>
			<div class="about-me-content">Nullam blandit gravida viverra. Etiam turpis erat, sagittis sit amet felis non, porta porta justo. Integer ornare nibh nulla, id pulvinar metus cursus semper. Vivamus dictum pellentesque mi. Vivamus ipsum tellus, mattis non ex sed, semper sodales ligula. Vivamus luctus lorem.</div>
		</div>
		<div class="btn-social-network-list">
			<a class="btn facebook-btn" href="#"><i class="fa fa-facebook" aria-hidden="true"></i>Facebook</a>
			<a class="btn google-btn" href="#"><i class="fa fa-google-plus" aria-hidden="true"></i>Google+</a>
			<a class="btn twitter-btn" href="#"><i class="fa fa-twitter" aria-hidden="true"></i>Twitter</a>
			<a class="btn linkedin-btn" href="#"><i class="fa fa-linkedin" aria-hidden="true"></i>Linkedin</a>
		</div>
		<p style="margin-bottom: 38px;"></p>
		<h3>パスワード編集</h3>
		<%= form_for(@user) do |f| %>
			<% if @user.errors[:password].length != 0%>
				<div class="error-messages text-danger"><%= @user.errors[:password][0] %></div>
			<% end %>
			<%= f.label :password, "新パスワード" %>
			<%= f.password_field :password, class: "form-control" %>

			<% if @user.errors[:password_confirmation].length != 0%>
				<div class="error-messages text-danger"><%= @user.errors[:password_confirmation][0] %></div>
			<% end %>
			<%= f.label :password_confirmation, "確認" %>
			<%= f.password_field :password_confirmation, class: "form-control" %>
			<p style="margin-bottom: 73px;"></p>
			<%= f.submit "パスワード更新", class: "btn btn-warning" %>
		<% end %>
	</div>
</div>
<script type="text/javascript">
	function readURL(input){
		if(input.files && input.files[0]){
			var reader = new FileReader();

			reader.onload = function(e){
				$("#avatar")
					.attr("src", e.target.result);
			};
			reader.readAsDataURL(input.files[0]);
		}
	}
	$("a.upload-new-pic").on("click",function(e){
		e.preventDefault();
		$("#upload-pic:hidden").trigger("click");
	});
	$("#upload-pic:hidden").change(function(){
		readURL(this);
	});
</script>

app/views/users/new.html.erb
<div id="login-box">
    <div class="left-block">
        <h1>サインアップ</h1>
        <%= form_for(@user, url: signup_path) do |f| %>
            <% if @user.errors[:name].length != 0 %>
                <div class="error-messages"><%= @user.errors[:name][0] %></div>
            <% end %>
            <%= f.text_field :name, placeholder: "Nobita Team", class: "form-control" %>

            <% if @user.errors[:email].length != 0 %>
                <div class="error-messages"><%= @user.errors[:email][0] %></div>
            <% end %>
            <%= f.email_field :email, placeholder: "nobita@gmail.com", class: "form-control" %>

            <% if @user.errors[:password].length != 0 %>
                <div class="error-messages"><%= @user.errors[:password][0] %></div>
            <% end %>
            <%= f.password_field :password, placeholder: "パスワード", class: "form-control" %>

            <% if @user.errors[:password_confirmation].length != 0 %>
                <div class="error-messages"><%= @user.errors[:password_confirmation][0] %></div>
            <% end %>
            <%= f.password_field :password_confirmation, placeholder: "パスワード確認", class: "form-control" %>
            <br>
            <%= f.submit "サインアップ" %>
        <% end %>
        <br>
        <p>すでにアカウントを持っている? <%= link_to "サインイン", login_path %></p>
    </div>
    <div class="right-block">

    </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="container user-profile">
	<br><br>
	<div class="row">
		<div class="col-xs-4">
			<div class="avatar">
				<% if @user.avatar? %>
					<%= image_tag @user.avatar.url(:thumb) %>
				<% else %>
					<% if @user.gender == "Male" %>
						<%= image_tag @user.avatar.default_url("ava-default-male.jpg") %>
					<% else %>
						<%= image_tag @user.avatar.default_url("ava-default-female.png") %>
					<% end %>
				<% end %>
			</div>
		</div>
		<div class="col-xs-8">
			<div class="name-express">
				<div class="name"><%= @user.name %></div>
				<div class="config-area">
					<% if current_user?(@user) %>
						<%= link_to "プロフィール編集", edit_user_path(current_user), id: "edit-profile-btn" %>
					<% else %>
						<%= render 'follow_form' if logged_in? %>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</div>