config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

    root 'static_pages#home'
    get '/signup', to: 'users#new'
    post '/signup', to: 'users#create'  # named routes
    get '/login', to: 'sessions#new'
    post '/login', to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy'
    get '/my_store', to: 'stores#my_store'
    post '/update_store', to: 'stores#update_store'
    get '/create_food', to: 'foods#new'
    get '/search', to: 'static_pages#search'

    resources :users
    resources :account_activations, only: [:edit]
    resources :password_resets,     only: [:new, :create, :edit, :update]
    get   '/resend_activation/:email', to: 'account_activations#resend_activation', :constraints => { :email => /[^\/]+/ }
    resources :stores
    resources :foods
    resources :reviews
    resources :conversations,:messages
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    mount ActionCable.server => '/cable'#khong co dong nay thi AC broadcast du lieu nhung cacs client se khong nhan duoc gi dau.
end

app/models/food.rb
class Food < ApplicationRecord
    has_many :food_pictures, dependent: :destroy
    validates :name, presence: true, length: {maximum: 100}
    validates :description, presence: true
    belongs_to :store
    delegate :user,to: :store
    has_many :reviews, dependent: :destroy

    def self.search name
        Food.where("name like ?", "%#{name}%")
    end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
    before_action :logged_in_user, only: [:create, :update, :destroy]

    def index
            @foods = Food.all.order('created_at ASC')
                .paginate(page: params[:page], per_page: 6)
    end

    def new
        @food = Food.new
    end

    def create
        @food = Food.new(food_params)
        if @food.save
            @food_picture = FoodPicture.create(food_id: @food.id, picture: picture_params[:picture1])
            @food_picture = FoodPicture.create(food_id: @food.id, picture: picture_params[:picture2])
            @food_picture = FoodPicture.create(food_id: @food.id, picture: picture_params[:picture3])
            flash[:info] = "創造された成功"
            redirect_to :back
        else
            flash[:danger] = @food.errors.full_messages.join(" & ")
            redirect_to :back
        end
    end

    def show
        @food = Food.find_by(id: params[:id])
        @rate_five = Review.where(food_id: @food.id).where(point: 5).count();
        @rate_four = Review.where(food_id: @food.id).where(point: 4).count();
        @rate_three = Review.where(food_id: @food.id).where(point: 3).count();
        @rate_two = Review.where(food_id: @food.id).where(point: 2).count();
        @rate_one = Review.where(food_id: @food.id).where(point: 1).count();
        @rate_zero = Review.where(food_id: @food.id).where(point: 0).count();
        if @food == nil
            not_found
        end
    end

    def update
        @food = Food.find(params[:id])
        if @food.update_attributes(food_params)
            if @food.food_pictures.count == 0
                @food_picture = FoodPicture.create(food_id: @food.id, picture: picture_params[:picture1])
                @food_picture = FoodPicture.create(food_id: @food.id, picture: picture_params[:picture2])
                @food_picture = FoodPicture.create(food_id: @food.id, picture: picture_params[:picture3])
            elsif @food.food_pictures.count == 1
                @food.food_pictures[0].update_attribute(:picture, picture_params[:picture1])
                @food_picture = FoodPicture.create(food_id: @food.id, picture: picture_params[:picture2])
                @food_picture = FoodPicture.create(food_id: @food.id, picture: picture_params[:picture3])
            elsif @food.food_pictures.count == 2
                @food.food_pictures[0].update_attribute(:picture, picture_params[:picture1])
                @food.food_pictures[1].update_attribute(:picture, picture_params[:picture2])
                @food_picture = FoodPicture.create(food_id: @food.id, picture: picture_params[:picture3])
            elsif @food.food_pictures.count == 3
                @food.food_pictures[0].update_attribute(:picture, picture_params[:picture1])
                @food.food_pictures[1].update_attribute(:picture, picture_params[:picture2])
                @food.food_pictures[2].update_attribute(:picture, picture_params[:picture3])
            end
            flash[:success] = "食べ物更新"
            redirect_to :back
        else
            redirect_to :back
        end
    end

    def destroy
        @food = Food.find(params[:id]).destroy
        flash[:success] = "食べ物が削除されました。"

        if @food.destroy
            redirect_to :back
        end
    end

    private
        def food_params
            params.require(:food).permit(:name, :price, :description, :store_id)
        end

        def picture_params
            params.require(:food).permit(:picture1, :picture2, :picture3)
        end
end

app/views/foods/_reviews.html.erb
<div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-9">
    <div class="event-item wow fadeInRight">
        <h4 class="show tip-left"><%= time_ago_in_words(review.created_at) %></h4>
        <div class="well padding5 owner-clear">
            <div class="media">
                <% if logged_in? && current_user.id == review.user.id%>

                    <div class="setting-s">
                        <div class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <b class="glyphicon glyphicon-remove"></b>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="edit-review" key="<%= review.id %>" data-toggle="modal" data-target="#editReviewModal<%= review.id %>">編集</a></li>
                                <li><%= link_to "削除", review_path(id: review.id), method: :delete, class: "delete-review" %></li>
                            </ul>
                        </div>
                    </div>
                <% end %>
                <div class="media-left">
                    <% if (review.user.avatar?) %>
                    <a href="/users/<%= review.user.id %>">
                        <img src="<%= review.user.avatar %>" class="media-object w-70-h-70" alt="library">
                    </a>
                    <%  else %>
                        <a href="/users/<%= review.user.id %>">
                            <%= image_tag review.user.avatar.default_url("avatar_default.jpg"), class: "media-object w-70-h-70"%>
                        </a>
                    <% end %>
                </div>
                <div class="media-body">
                    <a href="/users/<%= review.user.id %>">
                        <h4 class="media-heading list-inline list-unstyled rating-star">
                            <%= review.user.name %>
                            <% for i in 0..review.point-1 %>
                            <li class="active"><i class="fa fa-star"></i></li>
                            <% end %>
                        </h4>
                    </a>

                    <p class="content-review"><%= review.content %></p>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/foods/_reviews_form.html.erb
<div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-9">
    <h4 class="m-bottom5"><strong>レビューを追加</strong></h4>
</div>
<%= form_for(:review, url: reviews_path,remote: true) do |f| %>
    <div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-9 p-0">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <%= f.hidden_field :point, :value => nil, id: 'rating-review' %>
                <ul id="review-error" style="color: red"></ul>
                <%= f.text_area(:content, size: "50x5", :required => true, placeholder: "あなたのレビューを入力してください...", class: 'form-control bg-info b-r-0' ) %>
            </div>
        </div>
    </div>
    <div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-9 p-0">
        <div class="col-xs-12 col-sm-12 col-md-12">
        <% if logged_in? && current_user%>
            <%= f.hidden_field :user_id, :value => current_user.id %>
            <%= f.hidden_field :food_id, :value => food.id %>
            <%= f.submit " レビュー ", class: "btn-success btn" %>
            <% end %>
        </div>
    </div>
<% end %>

app/views/foods/_reviews_list.html.erb
<% @reviews = food.reviews %>
<% if (@reviews.length > 0) %>
    <% @reviews.reverse.each do |review| %>
        <div id="editReviewModal<%= review.id %>" class="modal fade" role="dialog">
            <div class="modal-dialog">

            <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                            <h4 class="modal-title center text-success">レビューを編集する</h4>
                    </div>
                    <div class="modal-body">
                        <%= form_for(review) do |f| %>
                                    <div class="form-group">
                                        <%= f.hidden_field :point, class: 'edit-rating-review' %>
                                        <%= f.text_area(:content, size: "50x5", :required => true, placeholder: "あなたのレビューを入力してください...", class: 'form-control bg-info b-r-0' ) %>
                                    </div>

                                <% if logged_in? && current_user%>
                                    <%= f.submit " 更新する ", class: "btn-warning btn" %>
                                <% end %>
                        <% end %>
                    </div>
                </div>

            </div>
        </div>
        <%= render 'foods/reviews', food: food, review: review %>
    <% end %>
<% end %>