config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

    root 'static_pages#home'
    get '/signup', to: 'users#new'
    post '/signup', to: 'users#create'  # named routes
    get '/login', to: 'sessions#new'
    post '/login', to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy'
    get '/my_store', to: 'stores#my_store'
    post '/update_store', to: 'stores#update_store'
    get '/create_food', to: 'foods#new'
    get '/search', to: 'static_pages#search'

    resources :users
    resources :account_activations, only: [:edit]
    resources :password_resets,     only: [:new, :create, :edit, :update]
    get   '/resend_activation/:email', to: 'account_activations#resend_activation', :constraints => { :email => /[^\/]+/ }
    resources :stores
    resources :foods
    resources :reviews
    resources :conversations,:messages
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    mount ActionCable.server => '/cable'#khong co dong nay thi AC broadcast du lieu nhung cacs client se khong nhan duoc gi dau.
end

app/views/layouts/_header.html.erb
<nav>
	<div class="nav-wrapper">
		<a href="/" class="brand-logo"><%= fa_icon "coffee" %> | ベトナムの料理</a>
		<%= form_tag search_path, method: "get", class: "foods-search form-group " do %>
			<%= text_field_tag :search, params[:search], class: "search-box search-form form-control", placeholder: "検索..." %>
		<% end %>
		<ul id="nav-mobile" class="right hide-on-med-and-down">
			<% if logged_in? %>
                <li><%= link_to "私の店", my_store_path %></li>
                <li><a href="#portfolio-path" onclick="internal_link_click(this)">料理</a></li>
				<li class="dropdown">
					<a href="#" class="dropdown" data-toggle="dropdown">
						<% if current_user.avatar? %>
							<%= image_tag current_user.avatar.url, id: "avatar-header" %>
						<% else %>
							<%= image_tag current_user.avatar.default_url("avatar_default.jpg"), id: "avatar-header" %>
						<% end %>
						<%= current_user.name %>
						<b class="caret"></b>
					</a>
					<ul class="dropdown-menu pull-right" style="width: 130px;">
						<li><%= link_to "プロフィール", edit_user_path(current_user) %></li>
						<li><%= link_to "ログアウト", logout_path, method: "delete" %></li>
					</ul>
				</li>
				<li class="dropdown" id="notifications">
					<% conversations=current_user.conversations.where(not_see_user_id: current_user.id)%>
					<a href="#" class="dropdown" data-toggle="dropdown">
						<%=conversations.size==0 ? nil : conversations.size%>												
					</a>
					<ul class="dropdown-menu pull-right" style="width: 200px;">
						<% conversations.each do |conv|%>
							<li id="<%=conv.id%>"><a><%= current_user.id==conv.user1_id ? conv.user2.try(:name) : conv.user1.try(:name) %></a></li>
						<% end %>	
					</ul>
				</li>
			<% else %>
					<li><a href="#portfolio-path" onclick="internal_link_click(this)">料理</a></li>
					<li><a href="/login">サインイン</a></li>
			<% end %>
		</ul>
	</div>
</nav>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-eval': "false" %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
	<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
	</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= full_title(yield(:title)) %></title>
		<meta name="turbolinks-cache-control" content="no-cache">
		<link rel="icon" type="image/png" href="/assets/icon.jpg">
		<%= render "layouts/rails_default" %>
		<%= render "layouts/shim" %>
	</head>
	<body>
		<%= render 'layouts/header' %>
		<% flash.each do |message_type, message| %>
			<%= content_tag(:div, sanitize(message), class: "alert alert-#{message_type}") %>
		<% end %>
		<%= yield %>
		<div id="conversations" class="row"></div>
	</body>
</html>